# Generated by Django 5.2 on 2025-04-16 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Annaapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='signup',
            new_name='signupmodel',
        ),
    ]
