# Generated by Django 5.2 on 2025-04-16 17:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Annaapp', '0002_rename_signup_signupmodel'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PetListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('species', models.CharField(max_length=50)),
                ('breed', models.CharField(max_length=100)),
                ('age', models.CharField(max_length=20)),
                ('gender', models.CharField(max_length=10)),
                ('vaccinated', models.BooleanField(default=False)),
                ('health_details', models.TextField(blank=True)),
                ('personality', models.TextField(blank=True)),
                ('reason_for_rehoming', models.TextField()),
                ('image', models.ImageField(upload_to='pet_uploads/')),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('adopted', 'Adopted')], default='pending', max_length=20)),
                ('date_posted', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
