# Generated by Django 5.2 on 2025-04-16 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Annaapp', '0003_petlisting'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='petlisting',
            name='reason_for_rehoming',
        ),
    ]
