# Generated by Django 5.2 on 2025-04-18 09:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Annaapp', '0005_appointment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100)),
                ('message', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PetBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pet_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('pet_type', models.CharField(choices=[('dogs', 'Dogs'), ('cats', 'Cats'), ('bird', 'Birds'), ('fish', 'Fish'), ('rabbits', 'Rabbits'), ('horses', 'Horses')], max_length=20)),
                ('breed', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('payment_method', models.CharField(choices=[('credit', 'Credit Card'), ('debit', 'Debit Card'), ('upi', 'UPI')], max_length=20)),
                ('booking_date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
