# Generated by Django 5.2 on 2025-04-18 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Annaapp', '0006_contactmessage_petbooking'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('breed', models.CharField(choices=[('SHIH-TZU', 'Shih-Tzu'), ('LABRADOR', 'Labrador'), ('MALTESE', 'Maltese'), ('GOLDEN_RETRIEVER', 'Golden Retriever'), ('BEAGLE', 'Beagle'), ('SIBERIAN_HUSKY', 'Siberian Husky'), ('GERMAN_SHEPHERD', 'German Shepherd'), ('BULLDOG', 'Bulldog'), ('POODLE', 'Poodle'), ('OTHER', 'Other')], max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='pets/')),
                ('view_count', models.IntegerField(default=0)),
                ('available', models.BooleanField(default=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
