# Generated by Django 5.2 on 2025-04-24 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Annaapp', '0007_pet'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactmessage',
            name='user',
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='subject',
            field=models.CharField(max_length=200),
        ),
    ]
