# Generated by Django 5.2 on 2025-04-25 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Annaapp', '0008_remove_contactmessage_user_contactmessage_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='appointment',
            name='phone',
            field=models.CharField(max_length=15),
        ),
    ]
