# Generated by Django 5.2 on 2025-04-25 09:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Annaapp', '0011_receipt'),
    ]

    operations = [
        migrations.AddField(
            model_name='petbooking',
            name='expected_delivery',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.DeleteModel(
            name='Receipt',
        ),
    ]
