# Generated by Django 5.2 on 2025-04-25 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Annaapp', '0012_petbooking_expected_delivery_delete_receipt'),
    ]

    operations = [
        migrations.RenameField(
            model_name='petbooking',
            old_name='booking_date',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='petbooking',
            name='expected_delivery',
        ),
        migrations.RemoveField(
            model_name='petbooking',
            name='user',
        ),
        migrations.AlterField(
            model_name='petbooking',
            name='payment_method',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='petbooking',
            name='pet_type',
            field=models.CharField(max_length=50),
        ),
    ]
