# Generated by Django 5.2 on 2025-04-25 13:29

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Annaapp', '0013_rename_booking_date_petbooking_created_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='petbooking',
            old_name='created_at',
            new_name='booking_date',
        ),
        migrations.AddField(
            model_name='petbooking',
            name='expected_delivery',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='petbooking',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='petbooking',
            name='payment_method',
            field=models.CharField(choices=[('credit', 'Credit Card'), ('debit', 'Debit Card'), ('upi', 'UPI')], max_length=20),
        ),
        migrations.AlterField(
            model_name='petbooking',
            name='pet_type',
            field=models.CharField(choices=[('dogs', 'Dogs'), ('cats', 'Cats'), ('bird', 'Birds'), ('fish', 'Fish'), ('rabbits', 'Rabbits'), ('horses', 'Horses')], max_length=20),
        ),
    ]
